type: object
required: []
properties:
  problem_format_version:
    type: string
    default: legacy
    alternatives:
      legacy: {}
  type:
    type: string
    default: pass-fail
    alternatives:
      pass-fail:
        forbid:
          grading/on_reject: grade
      scoring: {}
  name:
    type: string
  uuid:
    type: string
  author:
    type: string
  source:
    type: string
  source_url:
    type: string
    alternatives:
      ".+":
        require:
          source: ".+"
      "": {}
  license:
    type: string
    default: unknown
    alternatives:
      unknown: 
        warn: License is unknown
        require:
          rights_owner: ".+"
      cc0|cc by|cc by-sa|educational|permission:
        require:
          rights_owner: ".+"
      public domain:
        forbid:
          rights_owner: ".+"
  rights_owner:
    type: string
    parsing: rights-owner-legacy
  limits:
    type: object
    properties:
      time_multiplier:
        type: float
        default: 5
        alternatives:
          "0.0:": {}
      time_safety_margin:
        type: float
        default: 2
      memory:
        type: int
        default: copy-from:system_default/memory
        alternatives:
          "1:": {}
      output:
        type: int
        default: copy-from:system_default/output
        alternatives:
          "1:": {}
      code:
        type: int
        default: copy-from:system_default/code
        alternatives:
          "1:": {}
      compilation_time:
        type: int
        default: copy-from:system_default/compilation_time
        alternatives:
          "1:": {}
      compilation_memory:
        type: int
        default: copy-from:system_default/compilation_memory
        alternatives:
          "1:": {}
      validation_time:
        type: int
        default: copy-from:system_default/validation_time
        alternatives:
          "1:": {}
      validation_memory:
        type: int
        default: copy-from:system_default/validation_memory
        alternatives:
          "1:": {}
      validation_output:
        type: int
        default: copy-from:system_default/validation_output
        alternatives:
          "1:": {}
  validation:
    type: object
    parsing: legacy-validation
    properties:
      type:
        type: string
        alternatives:
          default:
            forbid:
              validation/interactive: true
              validation/score: true
          custom: {}
      interactive:
        type: bool
      score:
        type: bool
  validator_flags:
    type: string
  keywords:
    type: list
    parsing: space-separated-strings
    content:
      type: string
  grading:
    type: object
    properties:
      show_test_data_groups:
        type: bool
        alternatives:
          True:
            forbid:
                type: pass-fail
          False: {}
      on_reject:
        type: string
        default: worst_error
        flags:
          - deprecated
        alternatives:
          first_error: {}
          worst_error: {}
          grade: {}
      objective:
        type: string
        default: max
        alternatives:
          min: {}
          max: {}
      accept_score:
        type: float # Should actually be type string, add custom parsing?
        default: 1.0
        flags:
          - deprecated
      reject_score:
        type: float # Should actually be type string, add custom parsing?
        default: 0.0
        flags:
          - deprecated
      range:
        type: object
        parsing: min-max-float-string
        flags:
          - deprecated
        properties:
          min:
            type: float
            default: -.inf
          max:
            type: float
            default: .inf

